package co.edu.uniquindio.compilares.analixador.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARIMETICO, OPERADOR_LOGICO,PARENTESIS_IZQ,PARENTESIS_DER, PALABRA_RESERVADA, DESCONOCIDO
}